; Boolean checks
FALSE EQU 0
TRUE  EQU 1

; flag operations
	const_def
	const FLAG_RESET ; 0
	const FLAG_SET   ; 1
	const FLAG_TEST  ; 2

YELLOW_VERSION EQU 0
RED_VERSION    EQU 1
BLUE_VERSION   EQU 2
ANY_VERSION    EQU 3
RED_OR_BLUE    EQU 4

; wUniversalVariable values
USE_RED_OR_BLUE_GRAPHICS   EQU 42
VERSION_CHANGE_IN_PROGRESS EQU 69
